stages:
    - build
    - compose_up
    - pull_model
    - clean

build_job:
    stage: build
    script:
        - docker compose build web-service

compose_up_job:
    stage: compose_up
    script:
        - docker compose up -d

pull_ollama_model:
    stage: pull_model
    script:
        - docker compose exec ollama ollama pull translategemma:4b

clean:
    stage: clean
    script:
        - docker system prune -f
    