services:
  web-service:
    build: .
    ports: 
      - "8080:8080"
    depends_on: 
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"